# Data Analytics — Exercise 7.1: NumPy Essentials
## Patrick Green-Holloway | Date: 2026-05-19

This notebook uses NumPy to analyze weekly revenue data for five regional offices.
It calculates statistics, applies a 5% bonus, filters high-performing regions, and reshapes the data for 2-D analysis.

In [4]:
import numpy as np

revenue = np.array([52_400.0, 38_750.0, 61_200.0, 47_900.0, 55_650.0])

print(f"Array: {revenue}")
print(f"Dtype: {revenue.dtype}")
print(f"Shape: {revenue.shape}")

Array: [52400. 38750. 61200. 47900. 55650.]
Dtype: float64
Shape: (5,)


In [5]:
print("Revenue Statistics")
print(f"Total Revenue: ${np.sum(revenue):,.2f}")
print(f"Mean Revenue: ${np.mean(revenue):,.2f}")
print(f"Median Revenue: ${np.median(revenue):,.2f}")
print(f"Standard Deviation: ${np.std(revenue):,.2f}")
print(f"Minimum Revenue: ${np.min(revenue):,.2f}")
print(f"Maximum Revenue: ${np.max(revenue):,.2f}")

Revenue Statistics
Total Revenue: $255,900.00
Mean Revenue: $51,180.00
Median Revenue: $52,400.00
Standard Deviation: $7,578.03
Minimum Revenue: $38,750.00
Maximum Revenue: $61,200.00


In [6]:
revenue_bonus = revenue * 1.05
bonus_amount = revenue_bonus - revenue

print(f"Original Revenue: {revenue}")
print(f"Revenue With 5% Bonus: {revenue_bonus}")
print(f"Bonus Amount Per Region: {bonus_amount}")

Original Revenue: [52400. 38750. 61200. 47900. 55650.]
Revenue With 5% Bonus: [55020.  40687.5 64260.  50295.  58432.5]
Bonus Amount Per Region: [2620.  1937.5 3060.  2395.  2782.5]


In [7]:
above_avg = revenue > np.mean(revenue)

print(f"Above Average Mask: {above_avg}")
print(f"Above Average Revenue Values: {revenue[above_avg]}")
print(f"Number of Regions Above Average: {np.sum(above_avg)}")

Above Average Mask: [ True False  True False  True]
Above Average Revenue Values: [52400. 61200. 55650.]
Number of Regions Above Average: 3


In [8]:
revenue_column = revenue.reshape(5, 1)

print("Revenue Column Array:")
print(revenue_column)

q_data = np.vstack([revenue, revenue])

print("\n2-D Revenue Data:")
print(q_data)

row_totals = np.sum(q_data, axis=1)
column_means = np.mean(q_data, axis=0)

print(f"\nRow Totals: {row_totals}")
print(f"Column Region Means: {column_means}")

Revenue Column Array:
[[52400.]
 [38750.]
 [61200.]
 [47900.]
 [55650.]]

2-D Revenue Data:
[[52400. 38750. 61200. 47900. 55650.]
 [52400. 38750. 61200. 47900. 55650.]]

Row Totals: [255900. 255900.]
Column Region Means: [52400. 38750. 61200. 47900. 55650.]


In [9]:
import numpy as np

revenue = np.array([52_400.0, 38_750.0, 61_200.0, 47_900.0, 55_650.0])

print(f"Array: {revenue}")
print(f"Dtype: {revenue.dtype}")
print(f"Shape: {revenue.shape}")

print("\nRevenue Statistics")
print(f"Total Revenue: ${np.sum(revenue):,.2f}")
print(f"Mean Revenue: ${np.mean(revenue):,.2f}")
print(f"Median Revenue: ${np.median(revenue):,.2f}")
print(f"Standard Deviation: ${np.std(revenue):,.2f}")
print(f"Minimum Revenue: ${np.min(revenue):,.2f}")
print(f"Maximum Revenue: ${np.max(revenue):,.2f}")

revenue_bonus = revenue * 1.05
bonus_amount = revenue_bonus - revenue

print(f"\nOriginal Revenue: {revenue}")
print(f"Revenue With 5% Bonus: {revenue_bonus}")
print(f"Bonus Amount Per Region: {bonus_amount}")

above_avg = revenue > np.mean(revenue)

print(f"\nAbove Average Mask: {above_avg}")
print(f"Above Average Revenue Values: {revenue[above_avg]}")
print(f"Number of Regions Above Average: {np.sum(above_avg)}")

revenue_column = revenue.reshape(5, 1)

print("\nRevenue Column Array:")
print(revenue_column)

q_data = np.vstack([revenue, revenue])

print("\n2-D Revenue Data:")
print(q_data)

row_totals = np.sum(q_data, axis=1)
column_means = np.mean(q_data, axis=0)

print(f"\nRow Totals: {row_totals}")
print(f"Column Region Means: {column_means}")

Array: [52400. 38750. 61200. 47900. 55650.]
Dtype: float64
Shape: (5,)

Revenue Statistics
Total Revenue: $255,900.00
Mean Revenue: $51,180.00
Median Revenue: $52,400.00
Standard Deviation: $7,578.03
Minimum Revenue: $38,750.00
Maximum Revenue: $61,200.00

Original Revenue: [52400. 38750. 61200. 47900. 55650.]
Revenue With 5% Bonus: [55020.  40687.5 64260.  50295.  58432.5]
Bonus Amount Per Region: [2620.  1937.5 3060.  2395.  2782.5]

Above Average Mask: [ True False  True False  True]
Above Average Revenue Values: [52400. 61200. 55650.]
Number of Regions Above Average: 3

Revenue Column Array:
[[52400.]
 [38750.]
 [61200.]
 [47900.]
 [55650.]]

2-D Revenue Data:
[[52400. 38750. 61200. 47900. 55650.]
 [52400. 38750. 61200. 47900. 55650.]]

Row Totals: [255900. 255900.]
Column Region Means: [52400. 38750. 61200. 47900. 55650.]
