# Exercise 1.A NumPy: Manipulating Arrays

In [33]:
import numpy as np 

## Looping Through Arrays

In [34]:
import numpy as np

arrA = np.array([
    [11, 12, 13],
    [14, 15, 16]
])

print(arrA)

[[11 12 13]
 [14 15 16]]


In [35]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [36]:
for y in arrA:
    print(y * 2)

[22 24 26]
[28 30 32]


## They gave the same result?

In [37]:
for x in arrA:
    for y in x:
        loop_result = y * 2
        print(loop_result)

# It printed the results vertically this time because we are printing each element of the array separately, rather than printing the entire row at once. When we print the entire row, it is displayed horizontally as a single line. However, when we print each element individually, they are printed on separate lines, resulting in a vertical display of the results.

22
24
26
28
30
32


## Joining and Stacking Arrays

In [38]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [39]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [40]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1), axis=0)
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [41]:
stacked_array_2 = np.stack((joined_array_2, joined_array_2), axis=1)
print(stacked_array_2)

[[[11 12 13 11 12 13]
  [11 12 13 11 12 13]]

 [[14 15 16 14 15 16]
  [14 15 16 14 15 16]]]


In [42]:
another_joined_array_1 = np.concatenate((joined_array_1, arrA), axis=0)
print(another_joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [43]:
another_joined_array_2 = np.concatenate((joined_array_1, arrA), axis=1)
print(another_joined_array_2)

#All the input array dimensions must match except for the concatenation axis. The joined array will have the same number of dimensions as the input arrays. The shape of the joined array will be the same as the input arrays, except along the concatenation axis, where it will be the sum of the sizes of the input arrays along that axis.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [ ]:
h_stack = np.hstack((arrA, arrA))  # hstack stacks arrays horizontally, side by side.
v_stack = np.vstack((arrA, arrA))  # vstack stacks arrays vertically, one row on top of another.
d_stack = np.dstack((arrA, arrA))  # dstack stacks arrays by depth, creating a 3D-style array.

print("Horizontal Stack:")
print(h_stack)

print("\nVertical Stack:")
print(v_stack)

print("\nDepth Stack:")
print(d_stack)

Horizontal Stack:
[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]

Vertical Stack:
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]

Depth Stack:
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [ ]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)

#This split the array into 2 1 dimensional arrays.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
splitereno = np.split(joined_array_1, 2)
print(splitereno)

# This segments the array into 2 2-dimensional arrays. Each resulting array will contain half of the rows of the original array.


[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
splitereno = np.split(joined_array_1, 3)
print(splitereno)

# This gives a value error because the array cannot be split into 3 equal parts along the specified axis. The number of splits must be a divisor of the size of the array along that axis. In this case, since joined_array_1 has a shape that does not allow for an equal split into 3 parts, it raises an error.

ValueError: array split does not result in an equal division

## Searching and Replacing Array Values.

In [44]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [47]:
arrB = np.array([
    [7, 6],
    [13, 5],
    [7, 3]
])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)


print(arrB)

z = arrB < 7


arrC = arrB[z]


print(arrC)

print(arrB)


y = arrB >= 7


arrD = arrB[y]


print(arrD)

[[ 6  7]
 [ 5 13]
 [ 3  7]]
[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]
[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
